In [ ]:
import numpy as np
from random import randint

students = ['Alice','Bob','Charlie','Danny','Eshan']
subjects = ['Maths','science','geography']
grades = np.random.randint(60,100,size=(5,3))
print(f"grades of students\n'{grades}")
print(f"students\n'{students}")
print(f"subjects\n'{subjects}")

max_of_each_subject = np.max(grades,axis=0)
print(max_of_each_subject)

average_of_students = np.mean(grades,axis=1)
print(f"Average of students\n{average_of_students}")

average_of_subject = np.mean(grades,axis=0)
print(f"Average of students\n{average_of_subject}")

print()




grades of students
'[[67 79 95]
 [77 84 62]
 [84 82 60]
 [81 87 65]
 [87 76 76]]
students
'['Alice', 'Bob', 'Charlie', 'Danny', 'Eshan']
subjects
'['Maths', 'science', 'geography']
[87 87 95]
Average of students
[80.33333333 74.33333333 75.33333333 77.66666667 79.66666667]
Average of students
[79.2 81.6 71.6]
